source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

pod 'AsyncDisplayKit', '~> 1.2'
pod 'Faker', git: 'https://github.com/vadymmarkov/Faker', branch: 'swift-2.0'
pod 'Nimble', git: 'https://github.com/Quick/Nimble', branch: 'swift-2.0'
pod 'Quick', git: 'https://github.com/Quick/Quick', branch: 'swift-2.0'
pod 'Sugar', git: 'https://github.com/hyperoslo/Sugar'
