source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

pod 'Wall', path: '../../'
pod 'Faker', git: 'https://github.com/vadymmarkov/Faker'
pod 'Sugar', git: 'https://github.com/hyperoslo/Sugar'
