source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

pod 'Sugar', git: 'https://github.com/hyperoslo/Sugar'
pod 'Fakery'
pod 'AsyncDisplayKit', git: 'https://github.com/facebook/AsyncDisplayKit', branch: 'master'
pod 'Wall', path: '../../'
