source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

pod 'Sugar', git: 'https://github.com/hyperoslo/Sugar'
pod 'Faker', git: 'https://github.com/vadymmarkov/Faker', branch: 'swift-2.0'
pod 'SwiftyJSON', git: 'https://github.com/SwiftyJSON/SwiftyJSON.git', branch: 'xcode7'
pod 'AsyncDisplayKit', git: 'https://github.com/facebook/AsyncDisplayKit'
pod 'Wall', path: '../../'
